[package]
name = "lisper-epc"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace=true
lexpr.workspace = true
thiserror.workspace = true
smol.workspace = true
[lints]
workspace = true
